### ISSUE TITLE
Does not work on all files because of utf-8 error

### ISSUE THREAD

**Issue by secemp9** [AlexBuz/llama-zip#13]
I notice this only works on ASCII text files, and not on other files with more bytes density: https://freewavesamples.com/ouch-6
This one is 36322 bytes. It is obviously compressible so that's beside the point: 
```
cat Ouch-6.wav | xz -9f | wc -c
29344

```

Now for llama-zip:
```
python3 llama_zip.py  /mnt/sda2/llm_models/Meta-Llama-3-8B.Q8_0.gguf -c < Ouch-6.wav 
Traceback (most recent call last):
  File "llama_zip.py", line 340, in <module>
    main()
  File "llama_zip.py", line 313, in main
    string = " ".join(args.string) if args.string else sys.stdin.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 25: invalid start byte
```

Now I think this is happening because of the `sys.stdin.read()`, so I changed it to `sys.stdin.buffer.read()` and changed `tokens = model.tokenize(string.encode("utf-8"), add_bos=False)` to just `tokens = model.tokenize(string, add_bos=False)`, but then receive this error:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  invalid character
Aborted
```

**Comment by AlexBuz** [comment]
As it stands, llama-zip should work on any UTF-8-encoded text (not just ASCII). The `invalid character` error originates [in the Llama 3 tokenizer in `llama.cpp`](https://github.com/ggerganov/llama.cpp/blob/4bfe50f741479c1df1c377260c3ff5702586719e/unicode.cpp#L338), which [expects UTF-8-encoded text](https://github.com/ggerganov/llama.cpp/blob/4bfe50f741479c1df1c377260c3ff5702586719e/unicode.cpp#L26).

Adding support for non-UTF-8 input data would require somehow encoding the data to UTF-8 before passing it to the tokenizer. Of course, this could be accomplished naively by encoding to something like base64, for example, but I don't think that would be the best approach for the sake of maximizing the compression ratio. I have not yet put much thought into what *would* be the best approach, but it would presumably be something that preserves (as much as possible) parts of the input that are already valid UTF-8, avoiding unnecessary encoding that could hamper the model's ability to predict well.

I will need to think about this more, as compressing arbitrary binary data is something I would like to support. In the meantime, I will add some error catching to inform the user of this restriction.

**Comment by secemp9** [comment]
I think the best way would be to use a tokenizer that work on those files, or to train your own tokenizer from scratch on similar files (I can easily generate those files or find them if needed). The good news is you don't need to train it from scratch, and just can use say, a base tokenizer like the one from `tiktoken` library, and then train it on the problematic files to add additional tokens.

Problem is though, I tried to do that with the `tokenizers` and `tiktoken` library, and they both have the same utf-8 error, so training with those likely won't work directly, unless I'm wrong.

**Comment by AlexBuz** [comment]
I'm thinking it would be simpler to do something tokenizer-agnostic, such as using an escape sequence or taking advantage of code points in Unicode's private use areas to encode bytes that would be invalid under UTF-8.

**Comment by AlexBuz** [comment]
Compression of arbitrary binary data is now supported!
