### ISSUE TITLE
ollama version?

### ISSUE THREAD

**Issue by sokoow** [AlexBuz/llama-zip#14]
Hey, nice project! is there any chance for ollama version of it?

**Comment by AlexBuz** [comment]
Thank you! Both `llama-zip` and `ollama` depend on the same backend for LLM inference, `llama.cpp`, so any LLM that works with `ollama` should also work with `llama-zip`. Could you clarify what you're asking for?

**Comment by sokoow** [comment]
ah nevermind, somehow I thought that using ollama api is possible here, but after reading the source code I see it's not that easy
