### ISSUE TITLE
ever tried tinyllama or smaller llamas?

### ISSUE THREAD

**Issue by sprappcom** [AlexBuz/llama-zip#16]
what's the smallest llama usable for english?

**Comment by AlexBuz** [comment]
I have not tried tinyllama. There are so many LLMs to try and it takes a while to run them on the test corpus on my machine, so I just picked two of the most popular ones to test and include in the table. However, if you see that tinyllama (or any other LLM, for that matter) has particularly good performance, please let me know, and I'd be happy to consider adding it to the table!
