### ISSUE TITLE
possible to provide benchmark for these?

### ISSUE THREAD

**Issue by sprappcom** [AlexBuz/llama-zip#18]
https://bellard.org/ts_zip/

only book1 is shown.

```
[alice29.txt](https://en.wikipedia.org/wiki/Canterbury_corpus)	152089	48492	2.551	21713	1.142
[book1](https://en.wikipedia.org/wiki/Calgary_corpus)	768771	261116	2.717	137477	1.431
[enwik8](http://mattmahoney.net/dc/text.html)	100000000	24865244	1.989	13825741	1.106
[enwik9](http://mattmahoney.net/dc/text.html)	1000000000	213370900	1.707	135443237	1.084
[linux-1.2.13.tar](https://mirrors.edge.kernel.org/pub/linux/kernel/v1.2/linux-1.2.13.tar.xz)	9379840	1689468	1.441	1196859	1.021
```

**Comment by AlexBuz** [comment]
Thank you for your interest in llama-zip!

Although files like enwik8, enwik9, and linux-1.2.13.tar would be nice to add, they are quite large and I would not be able to compress them using llama-zip in a reasonable amount of time on my machine, so I have no plans to add them at the moment.

As for alice29.txt, I think the Calgary corpus already gives a nice variety of files that llama-zip can feasibly compress on a personal machine in a reasonable amount of time, so I can't say that I see the benefit of adding alice29.txt specifically. I'm sure there countless similarly-sized files that are also worth adding, but I'd also like to prevent the table size from getting out  of hand.
