### ISSUE TITLE
Question re: interpreting tokens per second

### ISSUE THREAD

**Issue by Jefferderp** [AlexBuz/llama-zip#21]
Hello! This is really interesting project, thanks for putting this together.

I'm experimenting with CPU-only inference, running small models 3B or under in sysram. I'm curious to see how the results compare to leaders like zpaq or cmix in terms of pure ratios.

I notice that when I run a job with a Q4 quantized model, the tok/s is *lower* than an equivalent Q8, despite the Q4 model having a smaller memory footprint. Therefore my question is, should I be interpreting the tok/s metric as the model's realtime *inference speed*? Or is this actually the *compression speed*, i.e. the rate at which the model is successfully predicting the next token? I'm assuming it's the latter, as a more intelligent model (i.e. a Q8) would naturally have a higher success rate - but I wanted to confirm regardless.

Thanks!

**Comment by Jefferderp** [comment]
Haha, this is hopelessly slow without a GPU or unified memory architecture. Still an interesting experiment. I'll install a GPU next.

**Comment by AlexBuz** [comment]
I'm glad you find llama-zip interesting!

To answer your question, the `tok/s` refers to the compression speed, but that should effectively be equivalent to the model's real-time inference speed. Whether or not the model predicts the next token "successfully" (i.e., by assigning it a higher probability than any other token), the model still has to predict the entire token probability distribution, as this is necessary to drive the arithmetic coder. This means that the speed of compression should not depend on how intelligent a model is. Perhaps your CPU is simply faster at inferencing Q8-quantized models?
